# Generated by Django 6.0.1 on 2026-01-27 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], max_length=5)),
                ('description', models.TextField(help_text='Detailed description of the item')),
                ('location', models.CharField(help_text='Where it was lost or found', max_length=255)),
                ('date_lost_found', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLAIMED', 'Claimed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('security_question', models.CharField(blank=True, help_text='Question for verifying ownership', max_length=255, null=True)),
                ('security_answer_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
